-- This is the official visual/runtime module allowlist. Modern protocol parsers
-- remain in C++; their optional interfaces are deliberately absent from this list.
return {
    client = {
        'client_styles',
        'client_locales',
        'client_topmenu',
        'client_background',
        'client_options',
        'client_entergame'
    },

    game = {
        'game_walk',
        'game_minimap',
        'game_healthinfo',
        'game_inventory',
        'game_mainpanel',
        'game_hotkeys',
        'game_questlog',
        'game_textmessage',
        'game_console',
        'game_outfit',
        'game_skills',
        'game_containers',
        'game_viplist',
        'game_battle',
        'game_npctrade',
        'game_textwindow',
        'game_playertrade',
        'game_bugreport',
        'game_playerdeath',
        'game_ruleviolation',
        'game_spelllist',
        'game_cooldown',
        'game_modaldialog',
        'game_unjustifiedpoints',
        'game_shaders'
    },

    disabledVisual = {
        'client_bottommenu',
        'client_debug_info',
        'client_serverlist',
        'client_terminal',
        'game_actionbar',
        'game_analyser',
        'game_attachedeffects',
        'game_blessing',
        'game_creatureinformation',
        'game_cyclopedia',
        'game_forge',
        'game_healthcircle',
        'game_highscore',
        'game_imbuementtracker',
        'game_imbuing',
        'game_inspect',
        'game_lootsplitter',
        'game_market',
        'game_notifications',
        'game_paperdolls',
        'game_playermount',
        'game_prey',
        'game_proficiency',
        'game_quickloot',
        'game_rewardwall',
        'game_shop',
        'game_stash',
        'game_store',
        'game_taskboard',
        'game_tutorial',
        'game_wheel'
    }
}
